{
 "title": "Cilium Operator",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "ENI", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "IP Addresses",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(cilium_operator_eni_ips) by (type)",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "EC2 API Interactions",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "dtdurations" }
   ],
   "targets": [
    {
     "expr": "rate(cilium_operator_eni_aws_api_duration_seconds_sum[1m])/rate(cilium_operator_eni_aws_api_duration_seconds_count[1m])",
     "legendFormat": "{{operation}} {{responseCode}}"
    }
   ]
  },
  {
   "title": "Number of nodes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "cilium_operator_eni_nodes", "legendFormat": "{{category}}" }
   ]
  },
  {
   "title": "# ENIs with addresses available",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "cilium_operator_eni_available", "legendFormat": "ENIs" }
   ]
  },
  {
   "title": "Metadata Resync Operations",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 9 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(cilium_operator_eni_resync_total[1m])",
     "legendFormat": "operations"
    }
   ]
  },
  {
   "title": "EC2 client side rate limiting",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "rate(cilium_operator_ec2_rate_limit_duration_seconds_sum[1m])/rate(cilium_operator_ec2_rate_limit_duration_seconds_count[1m])",
     "legendFormat": "{{operation}}"
    }
   ]
  },
  {
   "title": "ENI Creation",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "avg(rate(cilium_operator_eni_interface_creation_ops[1m])) by (subnetId, status)",
     "legendFormat": "{{status}} ({{subnetId}})"
    }
   ]
  }
 ]
}