{
 "title": "Cilium v1.7 Operator Metrics",
 "description": "Dashboard for the Cilium v1.7 (https://cilium.io/) Operator metrics",
 "tags": [
  "cilium",
  "operator"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Max File Descriptors",
   "type": "singlestat",
   "description": "Maximum file descriptors available for the Cilium Operator process",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 1 },
   "format": "short",
   "valueName": "avg",
   "targets": [
    {
     "expr": "cilium_operator_process_max_fds",
     "legendFormat": "Max File Descriptors"
    }
   ]
  },
  {
   "title": "Resident Memory",
   "type": "gauge",
   "description": "Resident memory of the Cilium Operator process",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 1 },
   "targets": [
    {
     "expr": "cilium_operator_process_resident_memory_bytes",
     "legendFormat": "Resident Memory"
    }
   ]
  },
  {
   "title": "Virtual Memory",
   "type": "gauge",
   "description": "Virtual memory of the Cilium Operator process",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 1 },
   "targets": [
    {
     "expr": "cilium_operator_process_virtual_memory_bytes",
     "legendFormat": "Virtual Memory"
    }
   ]
  },
  {
   "title": "Open File Descriptors",
   "type": "graph",
   "description": "Opened file descriptors by the Cilium Operator process",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "cilium_operator_process_open_fds",
     "legendFormat": "Opened FD"
    }
   ]
  },
  {
   "title": "Resident Memory",
   "type": "graph",
   "description": "Resident memory of the Cilium Operator process",
   "gridPos": { "h": 8, "w": 5, "x": 4, "y": 6 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "cilium_operator_process_resident_memory_bytes",
     "legendFormat": "Resident Memory"
    }
   ]
  }
 ]
}